onlyBuiltDependencies:
  - lefthook

packages:
  - "apps/*"
  - "packages/*"

publicHoistPattern:
  - "*eslint*"
  - "*playwright*"
  - "*prettier*"
  - "*storybook*"
  - "*stylelint*"

savePrefix: ""

sideEffectsCache: false
