blockExoticSubdeps: true

nodeLinker: isolated

onlyBuiltDependencies:
  - lefthook

packages:
  - "apps/*"
  - "packages/*"

publicHoistPattern:
  - "*playwright*"
  - "*storybook*"

savePrefix: ""

sideEffectsCache: false
