allowBuilds:
  esbuild: false
  lefthook: true
  sharp: false

blockExoticSubdeps: true

nodeLinker: isolated

packages:
  - "apps/*"
  - "packages/*"

publicHoistPattern:
  - "*playwright*"
  - "*storybook*"

savePrefix: ""

sideEffectsCache: false
